LOGGING:
  version: 1

  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG

  formatters:
    default:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      class: logging.Formatter

  disable_existing_loggers: false

  root:
    level: DEBUG
    handlers: [console]

  loggers:
    proton:
      level: INFO

    swim-adsb:
      level: DEBUG

BROKER:
  host: "rabbitmq:5671"
  cert_db: "/secrets/broker/ca_certificate.pem"
  cert_file: "/secrets/broker/client/client_certificate.pem"
  cert_key: "/secrets/broker/client/client_key.pem"

SUBSCRIPTION-MANAGER-API:
  host: "nginx:8443"
  https: true
  timeout: 30
  verify: "/secrets/web_server/ca_certificate.pem"
  username: ${SWIM_ADSB_SM_USER}
  password: ${SWIM_ADSB_SM_PASS}


ADSB:
  CITIES:
    Brussels: "EBBR"
    Amsterdam: "EHAM"
    Paris: "LFPG"
    Berlin: "EDDB"
    Athens: "LGAV"
    Heathrow: "EGLL"
  INTERVAL_IN_SEC: 5
  TRAFFIC_TIMESPAN_IN_DAYS: 1


